name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Downloads AutoPkg installer
      run: curl -L https://github.com/autopkg/autopkg/releases/download/v1.1/autopkg-1.1.pkg --output /tmp/autopkg.pkg
    - name: Installs AutoPkg
      run: sudo installer -pkg /tmp/autopkg.pkg -target /
    - name: Downloads Munki installer
      run: curl -L https://github.com/munki/munki/releases/download/v3.6.2/munkitools-3.6.2.3776.pkg --output /tmp/munkitools.pkg
    - name: Installs Munki
      run: sudo installer -pkg /tmp/munkitools.pkg -target /
    - name: Run a multi-line script
      run: |
        autopkg repo-add recipes
        mkdir /tmp/munki
        defaults write com.github.autopkg MUNKI_REPO /tmp/munki
        autopkg run -vv munkitools3.munki
    - uses: actions/upload-artifact@master
      with:
        name: my-artifact
        path: /tmp/munki/munkitools/
