name: CI

on: [push]

jobs:
  build:

    runs-on: macOS-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Downloads AutoPkg installer
      run: curl -L https://github.com/autopkg/autopkg/releases/download/v1.1/autopkg-1.1.pkg --output /tmp/autopkg.pkg
    - name: Downloads AutoPkg installer
      run: sudo installer -pkg /tmp/autopkg.pkg -target /
    - name: Run a multi-line script
      run: |
        autopkg repo-add recipes
        autopkg run -vv munkitools3.munki
